// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMfo1HZScR_1_kWlx1l7zsOkq98If2EMg',
    appId: '1:155359674969:web:a1e0030c12918d9eed2748',
    messagingSenderId: '155359674969',
    projectId: 'attendance-system-7d290',
    authDomain: 'attendance-system-7d290.firebaseapp.com',
    storageBucket: 'attendance-system-7d290.firebasestorage.app',
    measurementId: 'G-LXT84S4DBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6D0xR0Yx6U0D93yQJlG-zHq3s1lpQkro',
    appId: '1:155359674969:android:1e42d6d6de923a90ed2748',
    messagingSenderId: '155359674969',
    projectId: 'attendance-system-7d290',
    storageBucket: 'attendance-system-7d290.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Dz8iK-SDRy_sguauhrH2FSAab4qEPlI',
    appId: '1:155359674969:ios:856faa0752bbf465ed2748',
    messagingSenderId: '155359674969',
    projectId: 'attendance-system-7d290',
    storageBucket: 'attendance-system-7d290.firebasestorage.app',
    iosBundleId: 'com.example.attendanceManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Dz8iK-SDRy_sguauhrH2FSAab4qEPlI',
    appId: '1:155359674969:ios:856faa0752bbf465ed2748',
    messagingSenderId: '155359674969',
    projectId: 'attendance-system-7d290',
    storageBucket: 'attendance-system-7d290.firebasestorage.app',
    iosBundleId: 'com.example.attendanceManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMfo1HZScR_1_kWlx1l7zsOkq98If2EMg',
    appId: '1:155359674969:web:021956d10d0737d9ed2748',
    messagingSenderId: '155359674969',
    projectId: 'attendance-system-7d290',
    authDomain: 'attendance-system-7d290.firebaseapp.com',
    storageBucket: 'attendance-system-7d290.firebasestorage.app',
    measurementId: 'G-LV0MB7YW8Y',
  );
}
